"""remove admin

Revision ID: 76af0bef8313
Revises: 091de2a16763
Create Date: 2026-08-19 06:52:56.025663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76af0bef8313'
down_revision: Union[str, Sequence[str], None] = '091de2a16763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
